version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    networks:
      - laravel

  nginx:
    build: ./nginx
    container_name: laravel_nginx
    ports:
      - "8081:80"
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    ports:
      - "3307:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
